CREATE TABLE participants (
    participant_id VARCHAR(50) PRIMARY KEY,
    study_group VARCHAR(100) NOT NULL,
    condition_group VARCHAR(100),
    site VARCHAR(100),
    age INTEGER,
    gender VARCHAR(20)
);

CREATE TABLE ecg_metadata (
    ecg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    ecg_date DATE,
    qtc NUMERIC(10, 2),
    heart_rate NUMERIC(10, 2)
);
CREATE INDEX idx_pg_ecg_participant ON ecg_metadata(participant_id);

CREATE TABLE measurement (
    measurement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    measurement_date DATE,
    measurement_source_value VARCHAR(100),
    value_as_number NUMERIC(12, 3),
    unit_source_value VARCHAR(50)
);
CREATE INDEX idx_pg_measurement_person ON measurement(person_id);
CREATE INDEX idx_pg_measurement_source ON measurement(measurement_source_value);

CREATE TABLE condition_occurrence (
    condition_occurrence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    condition_start_date DATE,
    condition_source_value VARCHAR(100)
);
CREATE INDEX idx_pg_condition_person ON condition_occurrence(person_id);
CREATE INDEX idx_pg_condition_source ON condition_occurrence(condition_source_value);

CREATE TABLE cgm_daily (
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    mean_glucose NUMERIC(10, 2),
    std_glucose NUMERIC(10, 2),
    tir NUMERIC(10, 2),
    tar NUMERIC(10, 2),
    tbr NUMERIC(10, 2),
    measurement_count INTEGER,
    PRIMARY KEY (participant_id, day_index)
);
CREATE INDEX idx_pg_cgm_day ON cgm_daily(day_index);

CREATE TABLE activity_daily (
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    total_steps INTEGER,
    duration_minutes INTEGER,
    walking_duration INTEGER,
    running_duration INTEGER,
    sedentary_duration INTEGER,
    PRIMARY KEY (participant_id, day_index)
);
CREATE INDEX idx_pg_activity_day ON activity_daily(day_index);

CREATE TABLE heart_rate_daily (
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    mean_hr NUMERIC(10, 2),
    min_hr INTEGER,
    max_hr INTEGER,
    resting_hr INTEGER,
    PRIMARY KEY (participant_id, day_index)
);

CREATE TABLE sleep_daily (
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    total_sleep_minutes INTEGER,
    light_sleep_minutes INTEGER,
    deep_sleep_minutes INTEGER,
    rem_sleep_minutes INTEGER,
    awake_minutes INTEGER,
    sleep_efficiency NUMERIC(10, 2),
    PRIMARY KEY (participant_id, day_index)
);

CREATE TABLE spo2_daily (
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    mean_spo2 NUMERIC(10, 2),
    min_spo2 NUMERIC(10, 2),
    max_spo2 NUMERIC(10, 2),
    PRIMARY KEY (participant_id, day_index)
);

CREATE TABLE stress_daily (
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    mean_stress NUMERIC(10, 2),
    max_stress NUMERIC(10, 2),
    PRIMARY KEY (participant_id, day_index)
);

CREATE TABLE cgm_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    timestamp TIMESTAMP NOT NULL,
    glucose_mg_dl NUMERIC(10, 2)
);
CREATE INDEX idx_pg_cgm_readings_participant_day_time ON cgm_readings(participant_id, day_index, timestamp);

CREATE TABLE activity_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    timestamp TIMESTAMP NOT NULL,
    steps INTEGER,
    calories NUMERIC(10, 2),
    distance_km NUMERIC(10, 3)
);
CREATE INDEX idx_pg_activity_readings_participant_day_time ON activity_readings(participant_id, day_index, timestamp);

CREATE TABLE hr_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    timestamp TIMESTAMP NOT NULL,
    hr_bpm INTEGER
);

CREATE TABLE sleep_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    timestamp TIMESTAMP NOT NULL,
    sleep_stage VARCHAR(50),
    duration_minutes INTEGER
);

CREATE TABLE spo2_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    timestamp TIMESTAMP NOT NULL,
    spo2_percent NUMERIC(10, 2)
);

CREATE TABLE stress_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id VARCHAR(50) NOT NULL REFERENCES participants(participant_id),
    day_index INTEGER NOT NULL CHECK (day_index > 0),
    timestamp TIMESTAMP NOT NULL,
    stress_level INTEGER
);

INSERT INTO participants (participant_id, study_group, condition_group, site, age, gender) VALUES
    ('demo-001', 'healthy', 'healthy', 'Site A', 31, 'F'),
    ('demo-002', 'healthy', 'healthy', 'Site A', 45, 'M'),
    ('demo-003', 'insulin_dependent', 'insulin_dependent', 'Site B', 57, 'F'),
    ('demo-004', 'pre_diabetes_lifestyle_controlled', 'pre_diabetes_lifestyle_controlled', 'Site B', 63, 'M');

INSERT INTO ecg_metadata (participant_id, ecg_date, qtc, heart_rate) VALUES
    ('demo-001', DATE '2025-01-01', 410.00, 68.00),
    ('demo-002', DATE '2025-01-02', 425.00, 72.00),
    ('demo-003', DATE '2025-01-03', 438.00, 80.00);

INSERT INTO measurement (person_id, measurement_date, measurement_source_value, value_as_number, unit_source_value) VALUES
    ('demo-001', DATE '2025-01-01', 'HbA1c (%)', 5.20, '%'),
    ('demo-002', DATE '2025-01-02', 'HbA1c (%)', 5.60, '%'),
    ('demo-003', DATE '2025-01-03', 'HbA1c (%)', 8.10, '%'),
    ('demo-004', DATE '2025-01-04', 'HbA1c (%)', 6.20, '%'),
    ('demo-001', DATE '2025-01-01', 'Weight (kg)', 64.00, 'kg');

INSERT INTO condition_occurrence (person_id, condition_start_date, condition_source_value) VALUES
    ('demo-003', DATE '2025-01-03', 'Type 1 diabetes'),
    ('demo-004', DATE '2025-01-04', 'Prediabetes');

INSERT INTO cgm_daily (participant_id, day_index, mean_glucose, std_glucose, tir, tar, tbr, measurement_count) VALUES
    ('demo-001', 1, 98.00, 12.00, 96.00, 2.00, 2.00, 288),
    ('demo-001', 2, 101.00, 13.00, 94.00, 4.00, 2.00, 288),
    ('demo-002', 1, 105.00, 15.00, 92.00, 6.00, 2.00, 288),
    ('demo-002', 2, 108.00, 16.00, 90.00, 8.00, 2.00, 288),
    ('demo-003', 1, 164.00, 45.00, 61.00, 31.00, 8.00, 288),
    ('demo-003', 2, 172.00, 48.00, 55.00, 38.00, 7.00, 288),
    ('demo-004', 1, 132.00, 28.00, 78.00, 18.00, 4.00, 288),
    ('demo-004', 2, 137.00, 30.00, 74.00, 22.00, 4.00, 288);

INSERT INTO activity_daily (participant_id, day_index, total_steps, duration_minutes, walking_duration, running_duration, sedentary_duration) VALUES
    ('demo-001', 1, 8200, 74, 62, 12, 480),
    ('demo-001', 2, 7600, 63, 55, 8, 510),
    ('demo-002', 1, 6900, 52, 48, 4, 530),
    ('demo-002', 2, 7100, 56, 51, 5, 520),
    ('demo-003', 1, 4300, 33, 31, 2, 610),
    ('demo-003', 2, 3900, 29, 28, 1, 625),
    ('demo-004', 1, 5600, 42, 39, 3, 570),
    ('demo-004', 2, 5200, 38, 36, 2, 590);

INSERT INTO heart_rate_daily (participant_id, day_index, mean_hr, min_hr, max_hr, resting_hr)
SELECT participant_id, day_index, 72, 55, 130, 62 FROM activity_daily;
INSERT INTO sleep_daily (participant_id, day_index, total_sleep_minutes, light_sleep_minutes, deep_sleep_minutes, rem_sleep_minutes, awake_minutes, sleep_efficiency)
SELECT participant_id, day_index, 420, 250, 80, 90, 20, 92 FROM activity_daily;
INSERT INTO spo2_daily (participant_id, day_index, mean_spo2, min_spo2, max_spo2)
SELECT participant_id, day_index, 97, 94, 99 FROM activity_daily;
INSERT INTO stress_daily (participant_id, day_index, mean_stress, max_stress)
SELECT participant_id, day_index, 28, 55 FROM activity_daily;

INSERT INTO cgm_readings (participant_id, day_index, timestamp, glucose_mg_dl) VALUES
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:00:00', 96),
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:05:00', 99),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:00:00', 158),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:05:00', 166);
INSERT INTO activity_readings (participant_id, day_index, timestamp, steps, calories, distance_km) VALUES
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:00:00', 120, 5.2, 0.08),
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:05:00', 135, 5.8, 0.09),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:00:00', 60, 3.1, 0.04),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:05:00', 75, 3.6, 0.05);
INSERT INTO hr_readings (participant_id, day_index, timestamp, hr_bpm) VALUES
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:00:00', 68),
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:05:00', 70),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:00:00', 82),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:05:00', 84);
INSERT INTO sleep_readings (participant_id, day_index, timestamp, sleep_stage, duration_minutes) VALUES
    ('demo-001', 1, TIMESTAMP '2025-01-01 02:00:00', 'deep', 30),
    ('demo-003', 1, TIMESTAMP '2025-01-01 02:00:00', 'light', 30);
INSERT INTO spo2_readings (participant_id, day_index, timestamp, spo2_percent) VALUES
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:00:00', 98),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:00:00', 96);
INSERT INTO stress_readings (participant_id, day_index, timestamp, stress_level) VALUES
    ('demo-001', 1, TIMESTAMP '2025-01-01 08:00:00', 25),
    ('demo-003', 1, TIMESTAMP '2025-01-01 08:00:00', 42);

CREATE TABLE _docker_init_status (
    status VARCHAR(32) PRIMARY KEY,
    initialized_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO _docker_init_status (status) VALUES ('ready');

